version: '3.8'

services:

  pyicub:
    image: ${PYICUB_BASE_NAME:?err}.local
    container_name: pyicub.${VERSION}

    extends:
      file: .dockyman/profiles/local.yaml
      service: local

    env_file:
      - .env
      - icub.env
      - pyicub.env

    command: ["/bin/bash", "-c", "terminator & bash /var/dockyman/scripts/initContainer.sh"]
    
    volumes:
      - type: bind
        source: ./scripts
        target: /var/dockyman/scripts

      - type: bind
        source: ./workdir
        target: /workdir

      - type: volume
        source: pyicub-workspace
        target: /home/icub/pyicub


  pyicub-frontend:
    image: ${PYICUB_FRONTEND_BASE_NAME}
    container_name: pyicub-frontend.${PYICUB_FRONTEND_VERSION}

    profiles: ["restapi"]
  
    env_file:
      - .env
      - pyicub.env

    network_mode: host

    depends_on:
      - pyicub

    volumes:
      - type: volume
        source: pyicub-frontend-workspace
        target: /app/pyicub-frontend

volumes:
  pyicub-workspace:
  pyicub-frontend-workspace:
