# MIT License
#
# Copyright (c) 2022 Social Cognition in Human-Robot Interaction
#                    Author: Davide De Tommaso (davide.detommaso@iit.it)
#                    Project: Dockyman template
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

version: '3.8'

services:

  robotology:
    image: ${PJT_DOCKER_IMAGE}.local
    container_name: pyicub-lab.${RELEASE}

    extends:
      file: .dockyman/profiles/local.yml
      service: local

    environment:
      - ICUB_SIMULATION=true
      - ICUB_USER=icub
      - ICUB_PSW=icub
      - ICUB_HOST=icub-head
      - ICUB_IP=10.0.0.2
      - ICUBSRV_HOST=icubsrv
      - ICUBSRV_IP=10.0.0.1
      - ICUB_APPS=/usr/local/src/robot/applications

    command: ["/bin/bash", "-c", "terminator & bash /home/icub/shared/startup.sh"]

    working_dir: /home/icub/pyicub-lab

    volumes:
      - type: bind
        source: ./shared
        target: /home/icub/shared

      - type: volume
        source: pyicub-lab
        target: /home/icub/pyicub-lab

      - type: volume
        source: pyicub-vscode-server
        target: /home/icub/.vscode-server

      - type: volume
        source: pyicub-vscode-server-insiders
        target: /home/icub/.vscode-server-insiders


volumes:
  pyicub-lab:
  pyicub-vscode-server:
  pyicub-vscode-server-insiders:
