# MIT License
#
# Copyright (c) 2022 Social Cognition in Human-Robot Interaction
#                    Author: Davide De Tommaso (davide.detommaso@iit.it)
#                    Project: Dockyman template
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

version: '3.8'

services:

  pyicub:
    container_name: pyicub-lab.${RELEASE}
    image: ${PJT_DOCKER_IMAGE}.local

    build:
      context: .dockyman
      args:
        LOCAL_USER_ID: ${LOCAL_USER_ID}
        LOCAL_GROUP_ID: ${LOCAL_GROUP_ID}
        GROUP_AUDIO: ${GROUP_AUDIO}
        GROUP_VIDEO: ${GROUP_VIDEO}
        GROUP_INPUT: ${GROUP_INPUT}
        GROUP_DIALOUT: ${GROUP_DIALOUT}
        XDG_RUNTIME_DIR: ${XDG_RUNTIME_DIR}
        DOCKER_SRC: ${PJT_DOCKER_IMAGE}
        USERNAME: icub


    extends:
      file: ${BASE_SERVICE_FILENAME}
      service: ${BASE_SERVICE_NAME}

    environment:
        - PROJECT_NAME=${PROJECT_NAME}
        - RELEASE=${RELEASE}
        - ICUB_SIMULATION=true
        - ICUB_NAME=icubSim
        - ICUB_USER=icub
        - ICUB_PSW=icub
        - ICUB_HOST=icub-head
        - ICUB_APPS=/usr/local/src/robot/applications

    command: ["/bin/bash", "-c", "terminator & bash /home/icub/init.sh"]

    volumes:
      - type: bind
        source: ./shared
        target: /home/icub/shared

      - type: volume
        source: pyicub-lab
        target: /home/icub/pyicub-lab

      - type: volume
        source: pyicub-yarp-config
        target: /home/icub/.config/yarp/

      - type: volume
        source: pyicub-vscode-server
        target: /home/icub/.vscode-server

      - type: volume
        source: pyicub-vscode-server-insiders
        target: /home/icub/.vscode-server-insiders


volumes:
  pyicub-lab:
  pyicub-yarp-config:
  pyicub-vscode-server:
  pyicub-vscode-server-insiders:
