name: Dockyman build base image(s)

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
         
      - name: Build and Docker image
        run: |
          make -C .dockyman build
          
