name: Docker Release

on:
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
         username: ${{ secrets.DOCKER_USERNAME }}
         password: ${{ secrets.DOCKER_PASSWORD }}
                 
      - name: Build and push Docker image
        run: |
          docker login
          make -C .dockyman release VERSION=${{ github.event.release.tag_name }}
          make -C .dockyman build
          make -C .dockyman push
